# Generated by Django 3.1.7 on 2021-03-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_regis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='regis',
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
